"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 05:01:57.801534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuentes_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('agencia', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('licencia', sa.String(length=200), nullable=True),
    sa.Column('ultima_sincronizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('principios_activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dci_es', sa.String(length=200), nullable=False),
    sa.Column('dci_en', sa.String(length=200), nullable=False),
    sa.Column('atc', sa.String(length=50), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=False),
    sa.Column('terminos_openfda', sa.Text(), nullable=True),
    sa.Column('texto_busqueda', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dci_es')
    )
    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principios_activos_atc'), ['atc'], unique=False)
        batch_op.create_index(batch_op.f('ix_principios_activos_grupo'), ['grupo'], unique=False)

    op.create_table('productos_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=300), nullable=False),
    sa.Column('nombre_busqueda', sa.String(length=300), nullable=False),
    sa.Column('laboratorio', sa.String(length=300), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=200), nullable=True),
    sa.Column('via', sa.String(length=200), nullable=True),
    sa.Column('composicion', sa.Text(), nullable=True),
    sa.Column('tipo_producto', sa.String(length=100), nullable=True),
    sa.Column('categoria_registro', sa.String(length=100), nullable=True),
    sa.Column('n_registro', sa.String(length=100), nullable=True),
    sa.Column('es_generico', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('url_fuente', sa.String(length=500), nullable=True),
    sa.Column('url_ficha', sa.String(length=500), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente_id', 'id_externo')
    )
    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_comerciales_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_comerciales_nombre_busqueda'), ['nombre_busqueda'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_comerciales_pais'), ['pais'], unique=False)

    op.create_table('sincronizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('principio_activo_id', sa.Integer(), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('consulta', sa.Text(), nullable=True),
    sa.Column('n_recibidos', sa.Integer(), nullable=False),
    sa.Column('n_creados', sa.Integer(), nullable=False),
    sa.Column('n_actualizados', sa.Integer(), nullable=False),
    sa.Column('n_sin_cambios', sa.Integer(), nullable=False),
    sa.Column('n_no_listados', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.ForeignKeyConstraint(['principio_activo_id'], ['principios_activos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio_comercializacion', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_comerciales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presentaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presentaciones_producto_id'), ['producto_id'], unique=False)

    op.create_table('producto_principio',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('principio_activo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['principio_activo_id'], ['principios_activos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_comerciales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'principio_activo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_principio')
    with op.batch_alter_table('presentaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentaciones_producto_id'))

    op.drop_table('presentaciones')
    op.drop_table('sincronizaciones')
    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_comerciales_pais'))
        batch_op.drop_index(batch_op.f('ix_productos_comerciales_nombre_busqueda'))
        batch_op.drop_index(batch_op.f('ix_productos_comerciales_estado'))

    op.drop_table('productos_comerciales')
    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principios_activos_grupo'))
        batch_op.drop_index(batch_op.f('ix_principios_activos_atc'))

    op.drop_table('principios_activos')
    op.drop_table('fuentes_datos')
    # ### end Alembic commands ###
