"""filtro por nombre openfda

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 05:16:22.236489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filtro_nombre_openfda', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.drop_column('filtro_nombre_openfda')

    # ### end Alembic commands ###
