"""fichas tecnicas y monografias

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 05:28:22.295674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('autores', sa.Text(), nullable=True),
    sa.Column('publicacion', sa.String(length=300), nullable=True),
    sa.Column('fecha_publicacion', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('fecha_acceso', sa.String(length=10), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('fichas_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principio_activo_id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('set_id', sa.String(length=100), nullable=False),
    sa.Column('spl_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('fecha_efectiva', sa.String(length=10), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('laboratorio', sa.String(length=300), nullable=True),
    sa.Column('n_registro', sa.String(length=100), nullable=True),
    sa.Column('tipo_producto', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.ForeignKeyConstraint(['principio_activo_id'], ['principios_activos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principio_activo_id', 'fuente_id')
    )
    op.create_table('monografias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principio_activo_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=True),
    sa.Column('ficha_spl_id_base', sa.String(length=100), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publicada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_por', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas_tecnicas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principio_activo_id'], ['principios_activos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principio_activo_id', 'version')
    )
    with op.batch_alter_table('monografias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monografias_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_monografias_principio_activo_id'), ['principio_activo_id'], unique=False)

    op.create_table('secciones_ficha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas_tecnicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secciones_ficha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secciones_ficha_ficha_id'), ['ficha_id'], unique=False)

    op.create_table('pautas_posologicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monografia_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('indicacion', sa.String(length=300), nullable=False),
    sa.Column('poblacion', sa.String(length=20), nullable=False),
    sa.Column('dosis', sa.String(length=300), nullable=False),
    sa.Column('via', sa.String(length=100), nullable=False),
    sa.Column('frecuencia', sa.String(length=200), nullable=False),
    sa.Column('duracion', sa.String(length=200), nullable=True),
    sa.Column('dosis_maxima', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monografia_id'], ['monografias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pautas_posologicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pautas_posologicas_monografia_id'), ['monografia_id'], unique=False)

    op.create_table('secciones_monografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monografia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monografia_id'], ['monografias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monografia_id', 'tipo')
    )
    with op.batch_alter_table('secciones_monografia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secciones_monografia_monografia_id'), ['monografia_id'], unique=False)

    op.create_table('citas_pauta',
    sa.Column('pauta_id', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pauta_id'], ['pautas_posologicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referencia_id'], ['referencias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pauta_id', 'referencia_id')
    )
    op.create_table('citas_seccion',
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referencia_id'], ['referencias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_monografia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seccion_id', 'referencia_id')
    )
    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vias_openfda', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ficha_set_id_openfda', sa.String(length=100), nullable=True))

    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spl_set_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_productos_comerciales_spl_set_id'), ['spl_set_id'], unique=False)

    # ### end Alembic commands ###

    # Rellena spl_set_id de los productos ya sincronizados a partir del enlace a DailyMed.
    conexion = op.get_bind()
    productos = sa.table("productos_comerciales", sa.column("id"), sa.column("url_ficha"), sa.column("spl_set_id"))
    filas = conexion.execute(sa.select(productos.c.id, productos.c.url_ficha).where(productos.c.url_ficha.like("%setid=%")))
    for id_, url in filas.all():
        conexion.execute(
            productos.update().where(productos.c.id == id_).values(spl_set_id=url.split("setid=", 1)[1])
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_comerciales_spl_set_id'))
        batch_op.drop_column('spl_set_id')

    with op.batch_alter_table('principios_activos', schema=None) as batch_op:
        batch_op.drop_column('ficha_set_id_openfda')
        batch_op.drop_column('vias_openfda')

    op.drop_table('citas_seccion')
    op.drop_table('citas_pauta')
    with op.batch_alter_table('secciones_monografia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secciones_monografia_monografia_id'))

    op.drop_table('secciones_monografia')
    with op.batch_alter_table('pautas_posologicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pautas_posologicas_monografia_id'))

    op.drop_table('pautas_posologicas')
    with op.batch_alter_table('secciones_ficha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secciones_ficha_ficha_id'))

    op.drop_table('secciones_ficha')
    with op.batch_alter_table('monografias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monografias_principio_activo_id'))
        batch_op.drop_index(batch_op.f('ix_monografias_estado'))

    op.drop_table('monografias')
    op.drop_table('fichas_tecnicas')
    op.drop_table('referencias')
    # ### end Alembic commands ###
