"""cima

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 05:49:14.290781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('problema_suministro', sa.Boolean(), nullable=True))

    with op.batch_alter_table('secciones_ficha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones_ficha', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    with op.batch_alter_table('productos_comerciales', schema=None) as batch_op:
        batch_op.drop_column('problema_suministro')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
