"""listas esenciales

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 06:15:48.166684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_lista_esencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('principio_activo_id', sa.Integer(), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('lista', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('medicamento', sa.String(length=300), nullable=False),
    sa.Column('forma_farmaceutica', sa.String(length=200), nullable=False),
    sa.Column('concentracion', sa.String(length=200), nullable=False),
    sa.Column('atc', sa.String(length=20), nullable=True),
    sa.Column('uso_restringido', sa.Boolean(), nullable=False),
    sa.Column('aware', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('url_fuente', sa.String(length=500), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.ForeignKeyConstraint(['principio_activo_id'], ['principios_activos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente_id', 'codigo', 'forma_farmaceutica', 'concentracion')
    )
    with op.batch_alter_table('items_lista_esencial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_lista_esencial_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_lista_esencial_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_lista_esencial_principio_activo_id'), ['principio_activo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_lista_esencial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_lista_esencial_principio_activo_id'))
        batch_op.drop_index(batch_op.f('ix_items_lista_esencial_pais'))
        batch_op.drop_index(batch_op.f('ix_items_lista_esencial_estado'))

    op.drop_table('items_lista_esencial')
    # ### end Alembic commands ###
